version: '3.3'

services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 f_proj.wsgi:application --bin 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgres/data/

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:

